package com.famicom.mypollproject;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;

import com.famicom.mypollproject.accessingdatamysql.Poll;
import com.famicom.mypollproject.accessingdatamysql.PollRepository;


@RestController
public class MyPollProjectController {	
	
	////////////from here it goes correct
	@Autowired // This means to get the bean called userRepository
	// Which is auto-generated by Spring, we will use it to handle the data
	private PollRepository pollRepository;
	
	@GetMapping(path = "/getAllPolls")
	public @ResponseBody Iterable<Poll> getAllPolls() {
		// This returns a JSON or XML with the users
		return pollRepository.findAll();
	}

}